### ISSUE TITLE
CLI v0.3.2:`from moccasin.boa_tools import VyperContract`

### ISSUE THREAD

**Issue by Decentralisedme** [Cyfrin/moccasin#146]
Hello, I followed instruction to install moccasin using uv in .venv environment. 
- Python version 3.13
- uv installed
- mox --version: Moccasin CLI v0.3.2

Once I have activated the env `source /path/to/.venv/bin/activate`, I followed Quick Start: 1- initialised my project and then 2-open it in VSC (code .). 
In script/deploy.py: `from moccasin.boa_tools import VyperContract` is flagged as a problem: 'Import 'moccasin.boa_tools' could not be resolved'.  I tried to install in different ways also install it via:
`uv init
uv venv
source .venv/bin/activate`, 
same issue. I could not find similar issue: is there a way to solve it? let me know if any additional informations are needed

**Comment by PatrickAlphaC** [comment]
Yes! This is because your VSCode isn’t sure what the the correct virtual environment is. And your current virtual environment doesn’t have moccasin.

when you run `uv tool install moccasin` it installs it to its own isolated environment. If you want your VSCode to be able to flag it correctly, try this:

Run `uv add moccasin`, it should add it to your .venv. Run `uv venv` and then `uv sync`.

Then, in your VSCode, set the Python environment to that file in your .venv folder.

let me know if that’s not clear.

**Comment by PatrickAlphaC** [comment]
I'm going to close this as this is related to your VSCode setup. It might be good to add this info to the docs though...

**Comment by Decentralisedme** [comment]
Thank you Patrick, yes  by running `uv add moccasin` from the right folder (one up  from .venv) and then `cd  my_project` solved my issue.
